# if  TARGET_ARCH == I386_ARCH || TARGET_ARCH == X86_64_ARCH || TARGET_ARCH == AARCH64_ARCH
/* Sun-$Revision: 1.3 $ */

/* Copyright 1992-2012 AUTHORS.
   See the LICENSE file for license information. */

# pragma implementation "stubs_amd64.hh"
# include "_stubs_amd64.cpp.incl"

# pragma warn_unusedarg off


// asm routines (only needed for SIC:)



extern "C" {
  oop UncommonBranch(...) { fatal("unimp intel");  return NULL; }
  // Note: do not have a stack frame yet; link is link of caller
  // Also, they must preserve Temp1 and Temp2
  }

// Only needed for interpreter/compiler interoperation:
extern "C" {  oop ReturnResult_stub(...) { fatal("unimp intel");  return NULL; } }
oop ReturnResult_stub_result;


# if TARGET_ARCH == AARCH64_ARCH && !defined(SIC_COMPILER)
// Interpreter-only build (SELF_INTERP_ONLY): the SIC compiler and its generated
// trapdoor stubs are absent, but shared runtime code still takes the address of
// the send-message stubs as markers (sendDesc::lookupRoutine, nlrSupport's
// fix_current_return_address, frame asserts). No compiled code is ever entered
// in this build, so these addresses are never jumped to; return a stable,
// unique, non-null sentinel that can never alias a real nmethod entry.
// -- interpreter-only build
static char aarch64_interp_only_send_stub[2] = { 0, 0 };
char* aarch64_SendMessage_stub()   { return &aarch64_interp_only_send_stub[0]; }
char* aarch64_SendDIMessage_stub() { return &aarch64_interp_only_send_stub[1]; }
# endif

# if TARGET_ARCH == AARCH64_ARCH && defined(SIC_COMPILER)

extern "C" oop capture_NLR_parameters_from_registers(oop result,
                                                     smi target_frame,
                                                     int32 target_ID);
extern "C" {
  extern oop   NLRResultFromC;   // nlrSupport.cpp
  extern smi   NLRHomeFromC;
  extern int32 NLRHomeIDFromC;
}

// entry points handed to compiled senders whose send was interpreted by the
// VM (see sendDesc::sendMessage); set by generate_runtime_stubs_into
char* ReturnResult_entry = NULL;
char* ReturnNLR_entry    = NULL;

// EnterSelf: the C++ -> compiled-Self entry point.
//
// Generated into the stub zone at first use rather than written as static
// assembly: its inline sendDesc carries nmln words the runtime writes, and
// macOS text pages are immutable -- the JIT zone is the one writable+
// executable home.  Generating it also lets C++ supply the LookupType
// constant and lays the data block out via the same sendDesc offsets the
// compiler uses.
//
// The stub: builds a C frame record, saves the callee-saved registers
// compiled Self code may trash, reserves a Self outgoing area (lr hole at
// [sp+0], receiver at [sp+1], one argument at [sp+2]), and calls the
// nmethod.  Its return PC is the bottom-of-Self-stack sentinel
// (firstSelfFrame_returnPC) that frame walking terminates on, followed by
// the firstSelfFrame sendDesc.  An NLR arriving here behaves like a
// normal return (the result is already in x0).

oop (*EnterSelf_generated)(oop recv, char* entryPoint, oop arg1) = NULL;
oop (*EnterSelfN_generated)(oop recv, char* entryPoint, oop* args, int32 nargs) = NULL;
static char* SendMessage_stub_generated   = NULL;
static char* SendDIMessage_stub_generated = NULL;

// Most args EnterSelfN marshals into its fixed outgoing area: the area is
// (EnterSelfMaxArgs + 2) words (lr hole + receiver + args).  Routing
// (route_to_nmethod in interpreter.cpp) must not enter compiled code for a
// send with more arguments than this -- keep that cap in sync.
const fint EnterSelfMaxArgs = 14;

// the trapdoor-resident lookup stub that empty/missed inline caches call
char* aarch64_SendMessage_stub() {
  assert(SendMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendMessage_stub_generated;
}

// ditto, for dynamic-inheritance parent-check misses
char* aarch64_SendDIMessage_stub() {
  assert(SendDIMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendDIMessage_stub_generated;
}

void generate_EnterSelf() {
  // kept for the lazy first_sendDesc() hook; generation actually happens
  // in the Trapdoors constructor (zone init), which precedes any send
  fatal("EnterSelf should have been generated at zone init");
}

// SendMessage_stub: reached through a send site's target word on an
// inline-cache miss.  On entry lr is the send's return PC, which IS the
// sendDesc; the receiver and arguments sit in the sender's outgoing area
// ([sp+1] up), and fp is the sender's frame.  Call the C lookup (which
// compiles and rebinds the cache), then tail-jump to the returned entry
// point with lr restored so the callee's prologue saves the right PC.
static void generate_SendMessage_stub(Assembler* a) {
  a->Comment("SendMessage_stub");
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);          // a real frame record: link + pc-in-sender
  a->mov(fp, SP);                 // x29 -> our record: C callees then link to
                                  //   it, so frame walks during the lookup
                                  //   find a proper callee record of the
                                  //   sender ([+0]=its fp, [+8]=send-site pc)
                                  //   instead of dead-ending on a C record
                                  //   whose return pc (this stub) is outside
                                  //   code->contains
  a->mov(x0, lr);                 // ic = the sendDesc
  a->mov(x1, SP);                 // lookupFrame = this record (frame* = record
                                  //   whose [+8] points into the sending method)
  a->ldr(x2, SP, 16 + 1*oopSize); // receiver from sender's outgoing area
  a->mov(x3, PerformSelectorLoc);  // dynamic selector (perform sends; x19)
  a->mov(x4, PerformDelegateeLoc); // dynamic delegatee (x20)
  a->ldr(x5, SP, 16 + 2*oopSize);  // arg1 from the outgoing area
  a->loadAddressLiteral(x16, (void*)&SendMessage, VMAddressOperand);
  a->blr(x16);
  a->mov(x17, x0);                // target entry point
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->br(x17);
}

// Entered from a DI desc when a compiled method's assignable-parent check
// fails (genHelper_aarch64.cpp verifyOneImmediateParent).  At that point
// the method has not yet built its frame: lr is still the send's return PC
// (= the sendDesc), sp points at the caller's outgoing area, x9 holds the
// count of parents already verified, and x10 the DIDesc reference point.
static void generate_SendDIMessage_stub(Assembler* a) {
  a->Comment("SendDIMessage_stub");
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);          // frame record: link + pc-in-sender
  a->mov(fp, SP);                 // x29 -> our record (see SendMessage_stub)
  a->mov(x0, lr);                 // ic = the sendDesc
  a->mov(x1, SP);                 // lookupFrame = this record
  a->mov(x2, Temp2);              // DIDesc* (x10)
  a->mov(x3, Temp1);              // count of verified parents (x9)
  a->ldr(x4, SP, 16 + 1*oopSize); // receiver from sender's outgoing area
  a->ldr(x5, SP, 16 + 2*oopSize); // arg1 (pad word for 0-arg sends)
  a->loadAddressLiteral(x16, (void*)&SendDIMessage, VMAddressOperand);
  a->blr(x16);
  a->mov(x17, x0);                // recompiled nmethod's entry point
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->br(x17);
}

int32 generate_runtime_stubs_into(char* dst, int32 avail) {
  ResourceMark rm;
  Assembler* saved = theAssembler;
  Assembler* a = theAssembler = new Assembler(1024, 64, false, true);

  // EnterSelf and EnterSelfN are two C entry points that converge on ONE
  // call+return-PC+epilogue, so frame walking keeps a single bottom-of-Self
  // sentinel (firstSelfFrame_returnPC).  Both build their own C frame and
  // reserve the SAME fixed-size Self outgoing area (lr hole + receiver + up to
  // EnterSelfMaxArgs args, 16-byte aligned); the shared epilogue drops that
  // one size.  EnterSelf marshals the 0/1-arg case (its legacy C signature);
  // EnterSelfN marshals nargs args from a C array.
  const fint kOutWords = EnterSelfMaxArgs + 2;            // lr hole + rcvr + args
  const fint kOutBytes = (kOutWords + (kOutWords & 1)) * oopSize;   // 16-aligned
  Label common(a->printing);
  Label done(a->printing);
  Label nlr_through(a->printing);

  // ---- EnterSelf(recv=x0, entryPoint=x1, arg1=x2): the 0/1-arg entry ----
  fint enterSelf_offset = a->offset();                   // == 0; EnterSelf_generated
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);
  a->mov(fp, SP);
  a->sub(SP, SP, 80);
  for (fint i = 0; i < 5; i++)
    a->stp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->sub(SP, SP, kOutBytes);
  a->str(x0, SP, 1 * oopSize);       // receiver
  a->str(x2, SP, 2 * oopSize);       // the single argument (pad word for 0-arg)
  a->b(&common);

  // ---- EnterSelfN(recv=x0, entryPoint=x1, args=x2, nargs=x3): N-arg entry ----
  fint enterSelfN_offset = a->offset();
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);
  a->mov(fp, SP);
  a->sub(SP, SP, 80);
  for (fint i = 0; i < 5; i++)
    a->stp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->sub(SP, SP, kOutBytes);
  a->mov(x14, SP);                   // GP copy of the outgoing-area base (SP can't
                                     //   be an add's source register directly)
  a->str(x0, x14, 1 * oopSize);      // receiver
  // marshal args[0..nargs-1] -> outgoing [base + (2+i) words]
  a->mov(x11, x3);                   // remaining count
  a->mov_imm(x9, 0);                 // running byte offset (i * oopSize)
  Label mloop(a->printing);
  Label mdone(a->printing);
  mloop.define();
  a->cbz(x11, &mdone);
  a->add(x12, x2, x9);               // &args[i]
  a->ldr(x10, x12, 0);
  a->add(x13, x14, x9);              // &base[i]
  a->str(x10, x13, 2 * oopSize);     // -> base + i*oopSize + 2 words
  a->add(x9, x9, oopSize);
  a->sub(x11, x11, 1);
  a->b(&mloop);
  mdone.define();
  // fall through to the shared call

  // ---- shared call + return point + sendDesc + epilogue ----
  common.define();
  // the return PC after blr must be 8-aligned (it is the sendDesc address)
  if (((a->offset() + 4) & 7) != 0) a->nop();
  a->blr(x1);

  fint retPC_offset = a->offset();
  a->b(&done);                       // @0  branch around desc; normal return
  a->Data((int32)0, false);          // @4  mask
  a->b(&nlr_through);                // @8  NLR entry
  a->Data((int32)0, false);          // @12 pad
  a->DataPtr(0);                     // @16 jump_address (never rebound)
  a->DataPtr(0);                     // @24 nmln next
  a->DataPtr(0);                     // @32 nmln prev
  a->DataPtr(0);                     // @40 selector (static lookup: unused)
  a->DataPtr(smi(StaticNormalLookupType));  // @48 lookupType
  fint descEnd_offset = a->offset();
  done.define();

  // epilogue: drop outgoing area, restore registers, return (result in x0)
  a->add(SP, SP, kOutBytes);
  for (fint i = 0; i < 5; i++)
    a->ldp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->add(SP, SP, 80);
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->ret();

  // An NLR that propagates past the first Self frame must be recorded for
  // the C++ caller (sets _have_NLR_through_C and the *FromC globals) before
  // EnterSelf returns.  x0-x2 already hold result/home/homeID, matching the
  // C argument registers; the call returns the result in x0.
  nlr_through.define();
  a->loadAddressLiteral(x16, (void*)capture_NLR_parameters_from_registers,
                        VMAddressOperand);
  a->blr(x16);
  a->b(&done);

  a->align(8);
  fint sendMessage_offset = a->offset();
  generate_SendMessage_stub(a);

  a->align(8);
  fint sendDIMessage_offset = a->offset();
  generate_SendDIMessage_stub(a);

  // ReturnResult: a compiled sender's "callee" when the VM already
  // interpreted the send; just delivers the prepared result.
  a->Comment("ReturnResult");
  fint returnResult_offset = a->offset();
  a->loadAddressLiteral(x16, (void*)&ReturnResult_stub_result, VMAddressOperand);
  a->ldr(ResultReg, x16, 0);
  a->ret();

  // ReturnNLR: ditto, but an NLR escaped the interpreted callee; load the
  // NLR registers and divert to the send site's NLR entry (return PC + 8),
  // exactly like a compiled callee's NLR epilogue.
  a->Comment("ReturnNLR");
  fint returnNLR_offset = a->offset();
  a->loadAddressLiteral(x16, (void*)&NLRResultFromC, VMAddressOperand);
  a->ldr(NLRResultReg, x16, 0);
  a->loadAddressLiteral(x16, (void*)&NLRHomeFromC, VMAddressOperand);
  a->ldr(NLRHomeReg, x16, 0);
  a->loadAddressLiteral(x16, (void*)&NLRHomeIDFromC, VMAddressOperand);
  a->ldr32(NLRHomeIDReg, x16, 0);
  a->add(lr, lr, 8);
  a->ret();

  a->flushLiteralPool();   // &SendMessage literal; ldr-lit is pc-relative

  // copy into the trapdoor area (zone base, outside both the nmethod and
  // stub heaps -- so sendDesc::pic()/countStub() classify a freshly bound
  // lookup-routine target as 'none', exactly like i386's text-resident stubs)
  int32 len = a->instsLen();
  if (len > avail) fatal("trapdoor area too small for runtime stubs");
  {
    JITWriteScope ws;
    copy_bytes(a->instsStart, dst, len);
  }
  MachineCache::flush_instruction_cache_range(dst, dst + len);

  firstSelfFrame_returnPC   = dst + retPC_offset;
  firstSelfFrameSendDescEnd = dst + descEnd_offset;
  ReturnResult_entry        = dst + returnResult_offset;
  ReturnNLR_entry           = dst + returnNLR_offset;
  SendDIMessage_stub_generated = dst + sendDIMessage_offset;
  EnterSelf_generated  = (oop (*)(oop, char*, oop))(dst + enterSelf_offset);
  EnterSelfN_generated = (oop (*)(oop, char*, oop*, int32))(dst + enterSelfN_offset);
  SendMessage_stub_generated = dst + sendMessage_offset;

  // finish the first sendDesc so it behaves like any virgin inline cache:
  // target = the lookup routine, dependency links self-initialized
  // (nmln::rebind splices unconditionally, so {NULL,NULL} links crash)
  sendDesc* f = sendDesc::sendDesc_from_return_PC(firstSelfFrame_returnPC);
  {
    JITWriteScope ws;
    f->set_jump_addr(SendMessage_stub_generated);
    f->dependency()->init();
  }

  // self-check: the generated block must parse as the first sendDesc
  assert(f->raw_lookupType() == StaticNormalLookupType,
         "generated firstSelfFrame sendDesc has wrong lookup type");
  assert((char*)f + f->endOffset() == firstSelfFrameSendDescEnd,
         "generated firstSelfFrame sendDesc has wrong size");

  theAssembler = saved;
  return len;
}

# endif // TARGET_ARCH == AARCH64_ARCH && defined(SIC_COMPILER)

# endif // TARGET_ARCH == I386_ARCH || TARGET_ARCH == X86_64_ARCH || TARGET_ARCH == AARCH64_ARCH
