" This information was generated by the primitive maker (primitiveMaker.self). Please do not change it  manually. -- dmu 12/91  "

fribble frabble _AddSlots: ( |

  copy_color: copy_color Shape: shape = (
     copy_color: copy_color Shape: shape IfFail: 
      [|:e| ^error: 'primitive Inode::new failed: ', e]).

  copy_color: copy_color Shape: shape IfFail: failBlock = (
    copy_color _Inode_new_copy_color_Shape: shape ResultProxy: 
        inodeProto deadCopy IfFail: 
        [|:e| ^failBlock value: e]).


  delete = (
     deleteIfFail: 
      [|:e| ^error: 'primitive Inode::delete failed: ', e]).

  deleteIfFail: failBlock = (
     _Inode_delete_deleteIfFail: [|:e| ^failBlock value: e].
    self).


  errorNumber = (
     errorNumberIfFail: 
      [|:e| ^error: 'primitive ::errno failed: ', e]).

  errorNumberIfFail: failBlock = (
    "ignored" _errno_errorNumberIfFail: 
        [|:e| ^failBlock value: e]).


  errorNumber: errorNumber = (
     errorNumber: errorNumber IfFail: 
      [|:e| ^error: 'primitive ::errno failed: ', e]).

  errorNumber: errorNumber IfFail: failBlock = (
    errorNumber _errno_errorNumberIfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [errorNumber  asSmallInteger _errno_errorNumberIfFail: 
            [|:e| ^failBlock value: e]]].
    self).


  pr_zap = (
     pr_zapIfFail: 
      [|:e| ^error: 'primitive Pixrect::bark failed: ', e]).

  pr_zapIfFail: failBlock = (
     _Pixrect_bark_pr_zapResultProxy: 
        frobProto deadCopy IfFail: 
        [|:e| ^failBlock value: e]).


  pr_zap: pr_zap = (
     pr_zap: pr_zap IfFail: 
      [|:e| ^error: 'primitive Pixrect::bark failed: ', e]).

  pr_zap: pr_zap IfFail: failBlock = (
     _Pixrect_bark_pr_zap: pr_zap ResultProxy: 
      frobProto deadCopy IfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _Pixrect_bark_pr_zap: pr_zap  asSmallInteger ResultProxy: 
            frobProto deadCopy IfFail: 
            [|:e| ^failBlock value: e]]]).


  pr_zap: pr_zap = (
     pr_zap: pr_zap IfFail: 
      [|:e| ^error: 'primitive Pixrect::bark failed: ', e]).

  pr_zap: pr_zap IfFail: failBlock = (
     _Pixrect_bark_pr_zap: pr_zap ResultProxy: 
      frob xroto deadCopy IfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _Pixrect_bark_pr_zap: pr_zap  asSmallInteger ResultProxy: 
            frob xroto deadCopy IfFail: 
            [|:e| ^failBlock value: e]]]).


  time = (
     timeIfFail: 
      [|:e| ^error: 'primitive ::ftime failed: ', e]).

  timeIfFail: failBlock = (
    "ignored" _ftime_timeIfFail: [|:e| ^failBlock value: e]).


  open: open Mode: mode = (
     open: open Mode: mode IfFail: 
      [|:e| ^error: 'primitive ::open failed: ', e]).

  open: open Mode: mode IfFail: failBlock = (
    open _open_Mode: mode IfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [open  asByteVector _open_Mode: 
            mode  asSmallInteger IfFail: 
            [|:e| ^failBlock value: e]]]).


  open: open Mode: mode = (
     open: open Mode: mode IfFail: 
      [|:e| ^error: 'primitive ::open failed: ', e]).

  open: open Mode: mode IfFail: failBlock = (
    open _open_Mode: mode ResultProxy: pProto deadCopy IfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [open  asByteVector _open_Mode: 
            mode  asSmallInteger ResultProxy: 
            pProto deadCopy IfFail: 
            [|:e| ^failBlock value: e]]]).


  exit: exit = (
     exit: exit IfFail: 
      [|:e| ^error: 'primitive ::exit failed: ', e]).

  exit: exit IfFail: failBlock = (
    exit _exitIfFail: 
      [|:e| ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [exit  asSmallInteger _exitIfFail: 
            [|:e| ^failBlock value: e]]].
    self).


  exit: exit = (
     exit: exit IfFail: 
      [|:e| ^error: 'primitive ::exit failed: ', e]).

  exit: exit IfFail: failBlock = (
    exit _exitIfFail: [|:e| ^failBlock value: e].
    self).


| )


