" This information was generated by the primitive maker (primitiveMaker.self). Please do not change it  manually. -- dmu 12/91  "

traits pixrect _AddSlots: ( |

  copyOpen: copyOpen = (
     copyOpen: copyOpen 
      IfFail: [|:e| ^error: 'primitive ::pr_open failed: ', e]).

  copyOpen: copyOpen IfFail: failBlock = (
    copyOpen _pr_open_copyOpenResultProxy: pixrect copy 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [copyOpen  asByteVector 
            _pr_open_copyOpenResultProxy: pixrect copy 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  copyMemWidth: copyMemWidth Height: height Depth: depth = (
     copyMemWidth: copyMemWidth Height: height Depth: depth 
      IfFail: [|:e| ^error: 'primitive ::mem_create failed: ', e]).

  copyMemWidth: copyMemWidth Height: height Depth: depth 
    IfFail: failBlock = (
    copyMemWidth _mem_create_Height: height Depth: depth 
      ResultProxy: pixrect copy 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [copyMemWidth  asSmallInteger 
            _mem_create_Height: height  asSmallInteger 
            Depth: depth  asSmallInteger 
            ResultProxy: pixrect copy 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  pr_close = (
     
      pr_closeIfFail: [|:e| ^error: 'primitive ::pr_close failed: ', e]).

  pr_closeIfFail: failBlock = (
     _pr_closeIfFail: [|:n. :e| ^failBlock value: e].
    self).


  width = (
     
      widthIfFail: [|:e| ^error: 'primitive Pixrect::pr_width failed: ', e]).

  widthIfFail: failBlock = (
     
        _Pixrect_pr_width_widthIfFail: [|:n. :e| ^failBlock value: e]).


  height = (
     
      heightIfFail: [|:e| ^error: 'primitive Pixrect::pr_height failed: ', e]).

  heightIfFail: failBlock = (
     
        _Pixrect_pr_height_heightIfFail: [|:n. :e| ^failBlock value: e]).


  depth = (
     
      depthIfFail: [|:e| ^error: 'primitive Pixrect::pr_depth failed: ', e]).

  depthIfFail: failBlock = (
     
        _Pixrect_pr_depth_depthIfFail: [|:n. :e| ^failBlock value: e]).


  region_X: region_X Y: y W: w H: h = (
     region_X: region_X Y: y W: w H: h 
      IfFail: [|:e| ^error: 'primitive ::pr_region failed: ', e]).

  region_X: region_X Y: y W: w H: h IfFail: failBlock = (
     _pr_region_region_X: region_X Y: y W: w H: h 
      ResultProxy: pixrect copy 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_region_region_X: region_X  asSmallInteger 
            Y: y  asSmallInteger 
            W: w  asSmallInteger 
            H: h  asSmallInteger 
            ResultProxy: pixrect copy 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  polygon_2_DX: polygon_2_DX DY: dY NBnds: nBnds NPts: nPts 
    XList: xList 
    YList: yList 
    Op: op 
    Source: source 
    SX: sX 
    SY: sY = (
     polygon_2_DX: polygon_2_DX DY: dY NBnds: nBnds NPts: nPts 
      XList: xList 
      YList: yList 
      Op: op 
      Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:e| ^error: 'primitive ::pr_polygon_2_wrap failed: ', e]).

  polygon_2_DX: polygon_2_DX DY: dY NBnds: nBnds NPts: nPts 
    XList: xList 
    YList: yList 
    Op: op 
    Source: source 
    SX: sX 
    SY: sY 
    IfFail: failBlock = (
     _pr_polygon_2_wrap_polygon_2_DX: polygon_2_DX DY: dY 
      NBnds: nBnds 
      NPts: nPts 
      XList: xList 
      YList: yList 
      Op: op 
      Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ 
            _pr_polygon_2_wrap_polygon_2_DX: polygon_2_DX  asSmallInteger 
            DY: dY  asSmallInteger 
            NBnds: nBnds  asSmallInteger 
            NPts: nPts 
            XList: xList 
            YList: yList 
            Op: op  asSmallInteger 
            Source: source 
            SX: sX  asSmallInteger 
            SY: sY  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  lineSaveUnderMaxBytesXSize: lineSaveUnderMaxBytesXSize 
    YSize: ySize = (
     lineSaveUnderMaxBytesXSize: lineSaveUnderMaxBytesXSize 
      YSize: ySize 
      IfFail: [|:e| ^error: 'primitive ::lineSaveUnderMaxBytes failed: ', e]).

  lineSaveUnderMaxBytesXSize: lineSaveUnderMaxBytesXSize 
    YSize: ySize 
    IfFail: failBlock = (
    lineSaveUnderMaxBytesXSize 
      _lineSaveUnderMaxBytes_YSize: ySize 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [lineSaveUnderMaxBytesXSize  asSmallInteger 
            _lineSaveUnderMaxBytes_YSize: ySize  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Color: color 
    SaveUnder: saveUnder = (
     line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Color: color 
      SaveUnder: saveUnder 
      IfFail: [|:e| ^error: 'primitive ::lineSaveUnder failed: ', e]).

  line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Color: color 
    SaveUnder: saveUnder 
    IfFail: failBlock = (
     _lineSaveUnder_line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 
      Color: color 
      SaveUnder: saveUnder 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _lineSaveUnder_line_X0: line_X0  asSmallInteger 
            Y0: y0  asSmallInteger 
            X1: x1  asSmallInteger 
            Y1: y1  asSmallInteger 
            Color: color  asSmallInteger 
            SaveUnder: saveUnder  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  lineRestoreUnder: lineRestoreUnder = (
     lineRestoreUnder: lineRestoreUnder 
      IfFail: [|:e| ^error: 'primitive ::lineRestoreUnder failed: ', e]).

  lineRestoreUnder: lineRestoreUnder IfFail: failBlock = (
    lineRestoreUnder 
      _lineRestoreUnderIfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [lineRestoreUnder  asByteVector 
            _lineRestoreUnderIfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  planeMask: planeMask = (
     planeMask: planeMask 
      IfFail: [|:e| ^error: 'primitive ::pr_putattributes failed: ', e]).

  planeMask: planeMask IfFail: failBlock = (
     _pr_putattributes_planeMask: planeMask 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_putattributes_planeMask: planeMask  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  memToMemCopyFrom: memToMemCopyFrom Height: height = (
     memToMemCopyFrom: memToMemCopyFrom Height: height 
      IfFail: [|:e| ^error: 'primitive ::mem_to_mem_copy_prim failed: ', e]).

  memToMemCopyFrom: memToMemCopyFrom Height: height 
    IfFail: failBlock = (
     _mem_to_mem_copy_prim_memToMemCopyFrom: memToMemCopyFrom 
      Height: height 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _mem_to_mem_copy_prim_memToMemCopyFrom: memToMemCopyFrom 
            Height: height  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  memToScreenCopyFrom: memToScreenCopyFrom Height: height = (
     memToScreenCopyFrom: memToScreenCopyFrom Height: height 
      IfFail: [|:e| ^error: 'primitive ::mem_to_screen_copy_prim failed: ', e]).

  memToScreenCopyFrom: memToScreenCopyFrom Height: height 
    IfFail: failBlock = (
     
      _mem_to_screen_copy_prim_memToScreenCopyFrom: memToScreenCopyFrom 
      Height: height 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ 
            _mem_to_screen_copy_prim_memToScreenCopyFrom: memToScreenCopyFrom 
            Height: height  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  colorsShift: colorsShift Mask: mask = (
     colorsShift: colorsShift Mask: mask 
      IfFail: [|:e| ^error: 'primitive ::colorShift failed: ', e]).

  colorsShift: colorsShift Mask: mask IfFail: failBlock = (
     _colorShift_colorsShift: colorsShift Mask: mask 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _colorShift_colorsShift: colorsShift  asSmallInteger 
            Mask: mask  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  text_X: text_X Y: y Op: op Font: font Text: text = (
     text_X: text_X Y: y Op: op Font: font Text: text 
      IfFail: [|:e| ^error: 'primitive ::pr_text_wrap failed: ', e]).

  text_X: text_X Y: y Op: op Font: font Text: text 
    IfFail: failBlock = (
     _pr_text_wrap_text_X: text_X Y: y Op: op Font: font 
      Text: text 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_text_wrap_text_X: text_X  asSmallInteger 
            Y: y  asSmallInteger 
            Op: op  asSmallInteger 
            Font: font 
            Text: text  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  ttext_X: ttext_X Y: y Op: op Font: font Text: text = (
     ttext_X: ttext_X Y: y Op: op Font: font Text: text 
      IfFail: [|:e| ^error: 'primitive ::pr_ttext_wrap failed: ', e]).

  ttext_X: ttext_X Y: y Op: op Font: font Text: text 
    IfFail: failBlock = (
     _pr_ttext_wrap_ttext_X: ttext_X Y: y Op: op Font: font 
      Text: text 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_ttext_wrap_ttext_X: ttext_X  asSmallInteger 
            Y: y  asSmallInteger 
            Op: op  asSmallInteger 
            Font: font 
            Text: text  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  get_X: get_X Y: y = (
     get_X: get_X Y: y 
      IfFail: [|:e| ^error: 'primitive ::pr_get failed: ', e]).

  get_X: get_X Y: y IfFail: failBlock = (
     _pr_get_get_X: get_X Y: y 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_get_get_X: get_X  asSmallInteger Y: y  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  put_X: put_X Y: y Value: value = (
     put_X: put_X Y: y Value: value 
      IfFail: [|:e| ^error: 'primitive ::pr_put failed: ', e]).

  put_X: put_X Y: y Value: value IfFail: failBlock = (
     _pr_put_put_X: put_X Y: y Value: value 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_put_put_X: put_X  asSmallInteger Y: y  asSmallInteger 
            Value: value  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  vector_X0: vector_X0 Y0: y0 X1: x1 Y1: y1 Op: op 
    Value: value = (
     vector_X0: vector_X0 Y0: y0 X1: x1 Y1: y1 Op: op 
      Value: value 
      IfFail: [|:e| ^error: 'primitive ::pr_vector_wrap failed: ', e]).

  vector_X0: vector_X0 Y0: y0 X1: x1 Y1: y1 Op: op 
    Value: value 
    IfFail: failBlock = (
     _pr_vector_wrap_vector_X0: vector_X0 Y0: y0 X1: x1 Y1: y1 
      Op: op 
      Value: value 
      IfFail: [|:n. :e| 
('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_vector_wrap_vector_X0: vector_X0  asSmallInteger 
            Y0: y0  asSmallInteger 
            X1: x1  asSmallInteger 
            Y1: y1  asSmallInteger 
            Op: op  asSmallInteger 
            Value: value  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Brush: brush 
    Texture: texture 
    Op: op = (
     line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Brush: brush 
      Texture: texture 
      Op: op 
      IfFail: [|:e| ^error: 'primitive ::pr_line_wrap failed: ', e]).

  line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 Brush: brush 
    Texture: texture 
    Op: op 
    IfFail: failBlock = (
     _pr_line_wrap_line_X0: line_X0 Y0: y0 X1: x1 Y1: y1 
      Brush: brush 
      Texture: texture 
      Op: op 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_line_wrap_line_X0: line_X0  asSmallInteger 
            Y0: y0  asSmallInteger 
            X1: x1  asSmallInteger 
            Y1: y1  asSmallInteger 
            Brush: brush 
            Texture: texture 
            Op: op  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  rop_DX: rop_DX DY: dY DW: dW DH: dH Op: op Source: source 
    SX: sX 
    SY: sY = (
     rop_DX: rop_DX DY: dY DW: dW DH: dH Op: op Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:e| ^error: 'primitive ::pr_rop_wrap failed: ', e]).

  rop_DX: rop_DX DY: dY DW: dW DH: dH Op: op Source: source 
    SX: sX 
    SY: sY 
    IfFail: failBlock = (
     _pr_rop_wrap_rop_DX: rop_DX DY: dY DW: dW DH: dH Op: op 
      Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_rop_wrap_rop_DX: rop_DX  asSmallInteger 
            DY: dY  asSmallInteger 
            DW: dW  asSmallInteger 
            DH: dH  asSmallInteger 
            Op: op  asSmallInteger 
            Source: source 
            SX: sX  asSmallInteger 
            SY: sY  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  replrop_DX: replrop_DX DY: dY DW: dW DH: dH Op: op 
    Source: source 
    SX: sX 
    SY: sY = (
     replrop_DX: replrop_DX DY: dY DW: dW DH: dH Op: op 
      Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:e| ^error: 'primitive ::pr_replrop_wrap failed: ', e]).

  replrop_DX: replrop_DX DY: dY DW: dW DH: dH Op: op 
    Source: source 
    SX: sX 
    SY: sY 
    IfFail: failBlock = (
     _pr_replrop_wrap_replrop_DX: replrop_DX DY: dY DW: dW 
      DH: dH 
      Op: op 
      Source: source 
      SX: sX 
      SY: sY 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_replrop_wrap_replrop_DX: replrop_DX  asSmallInteger 
            DY: dY  asSmallInteger 
            DW: dW  asSmallInteger 
            DH: dH  asSmallInteger 
            Op: op  asSmallInteger 
            Source: source 
            SX: sX  asSmallInteger 
            SY: sY  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  stencil_DX: stencil_DX DY: dY DW: dW DH: dH Op: op 
    Stencil: stencil 
    StX: stX 
    StY: stY 
    From: from 
    SX: sX 
    SY: sY = (
     stencil_DX: stencil_DX DY: dY DW: dW DH: dH Op: op 
      Stencil: stencil 
      StX: stX 
      StY: stY 
      From: from 
      SX: sX 
      SY: sY 
      IfFail: [|:e| ^error: 'primitive ::pr_stencil_wrap failed: ', e]).

  stencil_DX: stencil_DX DY: dY DW: dW DH: dH Op: op 
    Stencil: stencil 
    StX: stX 
    StY: stY 
    From: from 
    SX: sX 
    SY: sY 
    IfFail: failBlock = (
     _pr_stencil_wrap_stencil_DX: stencil_DX DY: dY DW: dW 
      DH: dH 
      Op: op 
      Stencil: stencil 
      StX: stX 
      StY: stY 
      From: from 
      SX: sX 
      SY: sY 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_stencil_wrap_stencil_DX: stencil_DX  asSmallInteger 
            DY: dY  asSmallInteger 
            DW: dW  asSmallInteger 
            DH: dH  asSmallInteger 
            Op: op  asSmallInteger 
            Stencil: stencil 
            StX: stX  asSmallInteger 
            StY: stY  asSmallInteger 
            From: from 
            SX: sX  asSmallInteger 
            SY: sY  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  getColormapIndex: getColormapIndex Count: count Red: red 
    Green: green 
    Blue: blue = (
     getColormapIndex: getColormapIndex Count: count Red: red 
      Green: green 
      Blue: blue 
      IfFail: [|:e| ^error: 'primitive ::pr_getcolormap_wrap failed: ', e]).

  getColormapIndex: getColormapIndex Count: count Red: red 
    Green: green 
    Blue: blue 
    IfFail: failBlock = (
     _pr_getcolormap_wrap_getColormapIndex: getColormapIndex 
      Count: count 
      Red: red 
      Green: green 
      Blue: blue 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ 
            _pr_getcolormap_wrap_getColormapIndex: getColormapIndex  asSmallInteger 
            Count: count  asSmallInteger 
            Red: red  asByteVector 
            Green: green  asByteVector 
            Blue: blue  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  putColormapIndex: putColormapIndex Count: count Red: red 
    Green: green 
    Blue: blue = (
     putColormapIndex: putColormapIndex Count: count Red: red 
      Green: green 
      Blue: blue 
      IfFail: [|:e| ^error: 'primitive ::pr_putcolormap_wrap failed: ', e]).

  putColormapIndex: putColormapIndex Count: count Red: red 
    Green: green 
    Blue: blue 
    IfFail: failBlock = (
     _pr_putcolormap_wrap_putColormapIndex: putColormapIndex 
      Count: count 
      Red: red 
      Green: green 
      Blue: blue 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ 
            _pr_putcolormap_wrap_putColormapIndex: putColormapIndex  asSmallInteger 
            Count: count  asSmallInteger 
            Red: red  asByteVector 
            Green: green  asByteVector 
            Blue: blue  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


| )

traits region _AddSlots: ( |

  textBound_Length: textBound_Length Font: font Text: text = (
     textBound_Length: textBound_Length Font: font Text: text 
      IfFail: [|:e| ^error: 'primitive ::pf_textbound failed: ', e]).

  textBound_Length: textBound_Length Font: font Text: text 
    IfFail: failBlock = (
     _pf_textbound_textBound_Length: textBound_Length 
      Font: font 
      Text: text 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ 
            _pf_textbound_textBound_Length: textBound_Length  asSmallInteger 
            Font: font 
            Text: text  asByteVector 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  new = (
     
      newIfFail: [|:e| ^error: 'primitive pr_subregion:: failed: ', e]).

  newIfFail: failBlock = (
    region copy 
        _pr_subregion_newResultProxy: [|:n. :e| ^failBlock value: e]).


  delete = (
     
      deleteIfFail: [|:e| ^error: 'primitive pr_subregion:: failed: ', e]).

  deleteIfFail: failBlock = (
     
        _pr_subregion_deleteIfFail: [|:n. :e| ^failBlock value: e].
    self).


| )

traits pixfont _AddSlots: ( |

  pf_close = (
     
      pf_closeIfFail: [|:e| ^error: 'primitive ::pf_close failed: ', e]).

  pf_closeIfFail: failBlock = (
     _pf_closeIfFail: [|:n. :e| ^failBlock value: e].
    self).


  copyOpen: copyOpen = (
     copyOpen: copyOpen 
      IfFail: [|:e| ^error: 'primitive ::pf_open failed: ', e]).

  copyOpen: copyOpen IfFail: failBlock = (
    copyOpen _pf_open_copyOpenResultProxy: pixfont copy 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [copyOpen  asByteVector 
            _pf_open_copyOpenResultProxy: pixfont copy 
            IfFail: [|:n. :e| ^failBlock value: e]]]).


  basicFontSize = (
     
      basicFontSizeIfFail: [|:e| ^error: 'primitive ::pf_defaultsize_wrap failed: ', e]).

  basicFontSizeIfFail: failBlock = (
     
        _pf_defaultsize_wrap_basicFontSizeResultProxy: pr_size copy 
        IfFail: [|:n. :e| ^failBlock value: e]).


| )

traits position _AddSlots: ( |

  x = (
     xIfFail: [|:e| ^error: 'primitive pr_pos::x failed: ', e]).

  xIfFail: failBlock = (
     _pr_pos_x_xIfFail: [|:n. :e| ^failBlock value: e]).


  y = (
     yIfFail: [|:e| ^error: 'primitive pr_pos::y failed: ', e]).

  yIfFail: failBlock = (
     _pr_pos_y_yIfFail: [|:n. :e| ^failBlock value: e]).


  x: x = (
     x: x 
      IfFail: [|:e| ^error: 'primitive pr_pos::x failed: ', e]).

  x: x IfFail: failBlock = (
     _pr_pos_x_x: x 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_pos_x_x: x  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  y: y = (
     y: y 
      IfFail: [|:e| ^error: 'primitive pr_pos::y failed: ', e]).

  y: y IfFail: failBlock = (
     _pr_pos_y_y: y 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_pos_y_y: y  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


| )

traits pr_size _AddSlots: ( |

  x = (
     
      xIfFail: [|:e| ^error: 'primitive pr_size::x failed: ', e]).

  xIfFail: failBlock = (
     _pr_size_x_xIfFail: [|:n. :e| ^failBlock value: e]).


  y = (
     
      yIfFail: [|:e| ^error: 'primitive pr_size::y failed: ', e]).

  yIfFail: failBlock = (
     _pr_size_y_yIfFail: [|:n. :e| ^failBlock value: e]).


  x: x = (
     x: x 
      IfFail: [|:e| ^error: 'primitive pr_size::x failed: ', e]).

  x: x IfFail: failBlock = (
     _pr_size_x_x: x 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_size_x_x: x  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


  y: y = (
     y: y 
      IfFail: [|:e| ^error: 'primitive pr_size::y failed: ', e]).

  y: y IfFail: failBlock = (
     _pr_size_y_y: y 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_size_y_y: y  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


| )

traits brush _AddSlots: ( |

  new = (
     
      newIfFail: [|:e| ^error: 'primitive pr_brush:: failed: ', e]).

  newIfFail: failBlock = (
    brush copy 
        _pr_brush_newResultProxy: [|:n. :e| ^failBlock value: e]).


  delete = (
     
      deleteIfFail: [|:e| ^error: 'primitive pr_brush:: failed: ', e]).

  deleteIfFail: failBlock = (
     _pr_brush_deleteIfFail: [|:n. :e| ^failBlock value: e].
    self).


  width = (
     
      widthIfFail: [|:e| ^error: 'primitive pr_brush::width failed: ', e]).

  widthIfFail: failBlock = (
     
        _pr_brush_width_widthIfFail: [|:n. :e| ^failBlock value: e]).


  width: width = (
     width: width 
      IfFail: [|:e| ^error: 'primitive pr_brush::width failed: ', e]).

  width: width IfFail: failBlock = (
     _pr_brush_width_width: width 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_brush_width_width: width  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


| )

traits texture _AddSlots: ( |

  delete = (
     
      deleteIfFail: [|:e| ^error: 'primitive pr_texture:: failed: ', e]).

  deleteIfFail: failBlock = (
     _pr_texture_deleteIfFail: [|:n. :e| ^failBlock value: e].
    self).


  offset = (
     
      offsetIfFail: [|:e| ^error: 'primitive pr_texture::offset failed: ', e]).

  offsetIfFail: failBlock = (
     
        _pr_texture_offset_offsetIfFail: [|:n. :e| ^failBlock value: e]).


  offset: offset = (
     offset: offset 
      IfFail: [|:e| ^error: 'primitive pr_texture::offset failed: ', e]).

  offset: offset IfFail: failBlock = (
     _pr_texture_offset_offset: offset 
      IfFail: [|:n. :e| (reflect: e) isReflecteeString ifFalse: [e _Breakpoint]. ('badTypeError' isPrefixOf: e)   ifFalse: [^failBlock value: e]   True: [ _pr_texture_offset_offset: offset  asSmallInteger 
            IfFail: [|:n. :e| ^failBlock value: e]]].
    self).


| )


