 '$Revision:$'
 '
Copyright 1992-2009 AUTHORS, Sun Microsystems, Inc. and Stanford University.
See the LICENSE file for license information.
'


 '-- Module body'

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot'
        
         harold_hacks = bootstrap define: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () ToBe: bootstrap addSlotsTo: (
             bootstrap remove: 'directory' From:
             bootstrap remove: 'fileInTimeString' From:
             bootstrap remove: 'myComment' From:
             bootstrap remove: 'postFileIn' From:
             bootstrap remove: 'revision' From:
             bootstrap remove: 'subpartNames' From:
             globals modules init copy ) From: bootstrap setObjectAnnotationOf: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( |
             {} = 'ModuleInfo: Creator: globals modules harold_hacks.

CopyDowns:
globals modules init. copy 
SlotsToOmit: directory fileInTimeString myComment postFileIn revision subpartNames.

\x7fIsComplete: '.
            | ) .
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot\x7fVisibility: public'
        
         directory <- 'applications/allKorz'.
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: InitializeToExpression: (_CurrentTimeString)\x7fVisibility: public'
        
         fileInTimeString <- _CurrentTimeString.
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot'
        
         myComment <- ''.
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot'
        
         postFileIn = ( |
            | resend.postFileIn).
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot\x7fVisibility: public'
        
         revision <- '$Revision:$'.
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'globals' -> 'modules' -> 'harold_hacks' -> () From: ( | {
         'ModuleInfo: Module: harold_hacks InitialContents: FollowSlot\x7fVisibility: private'
        
         subpartNames <- ''.
        } | ) 

 bootstrap addSlotsTo: bootstrap stub -> 'traits' -> 'quartz' -> 'platformWindow' -> () From: ( | {
         'Category: generated by primitiveMaker\x7fModuleInfo: Module: harold_hacks InitialContents: FollowSlot\x7fVisibility: public'
        
         warpPointerToX: t0 Y: t1 IfFail: fb = ( |
            | 
            [
               _QuartzWindow_warp_pointerwarpPointerToX: t0 Y: t1 IfFail: 

              [|:e| ('badTypeError'   isPrefixOf: e)
                ||  ['deadProxyError' isPrefixOf: e]
                   ifFalse: [^fb value: e] 
                      True: [
                          ( reviveIfFail: [|:e| ^ fb value: e]) _QuartzWindow_warp_pointerwarpPointerToX: t0 asSmallInteger 
                            Y: t1 asSmallInteger IfFail: fb 
                   ]] .
            ] value.
            self).
        } | ) 



 '-- Side effects'

 globals modules harold_hacks postFileIn
